version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf

sphinx:
  fail_on_warning: false

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs